#!/usr/bin/env bash
# dotfiles are config files for common programs
# This script inserts symlinks in dotfile locations to this version controlled directory
# Thus changes will instantly reflect across all systems that share this folder
DOTFILE_LOCATION=$(find / -type d -iname dotfiles 2> /dev/null | head -n 1)

# INSTALL BASHRC AS SYMLINK
if [ -e "$HOME/.bashrc" ] ; then rm "$HOME/.bashrc" ; fi
ln -s "$DOTFILE_LOCATION/.bashrc" "$HOME/.bashrc"
ln -s "$DOTFILE_LOCATION/.colors" "$HOME/.colors"
echo 'bashrc done'

# INSTALL VIMRC AS SYMLINK -- deprecate in favor of micro
if [ -e "$HOME/.vimrc" ] ; then rm "$HOME/.vimrc" ; fi
ln -s "$DOTFILE_LOCATION/.vimrc" "$HOME/.vimrc"
echo 'vimrc done'

# INSTALL TMUX AS SYMLINK
if [ -e "$HOME/.tmux.conf" ] ; then rm "$HOME/.tmux.conf" ; fi
ln -s "$DOTFILE_LOCATION/.tmux.conf" "$HOME/.tmux.conf"
echo 'tmux done'

# INSTALL MICRO SETTINGS AS SYMLINK
if [ -e "$HOME/.config/micro/settings.json" ] ; then rm "$HOME/.config/micro/settings.json"; fi
ln -s "$DOTFILE_LOCATION/micro-settings.json" "$HOME/.config/micro/settings.json"
echo 'micro done'

# INSTALL VIM PLUGINS
mkdir -p ~/.vim/pack/nickg/start
# PRETTIER
git clone https://github.com/prettier/vim-prettier ~/.vim/pack/nickg/start/vim-prettier
# FZF
git clone https://github.com/junegunn/fzf ~/.vim/pack/nickg/start/fzf
# VIM-COMMENTARY
git clone https://tpope.io/vim/commentary.git ~/.vim/pack/nickg/start/vim-commentary
